// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wikbqrasvmggxbhlwazz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpa2JxcmFzdm1nZ3hiaGx3YXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMDMyOTksImV4cCI6MjA1MzU3OTI5OX0.L0lGB_dTO8ANKfUNtWI8Yyip6VYxOTnfldidDkP0-M8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);